use super::ast::{
    Statement,
    Expression,
    Symbol
};

use crate::lexer::{
    token::Token,
    error::LexingError
};

grammar;

extern {
    type Location = usize;
    type Error = LexingError;

    enum Token {
        "id" => Token::Identifier(<String>),
        "echo" => Token::Echo,
        "sit" => Token::Sit,
        "catena" => Token::Catena(<String>),
        ":" => Token::Column
    }
}

pub Program: Vec<Statement> = {
    <stmts:Stmt*> => stmts
}

Stmt: Statement = {
    StmtPrint,
    StmtVariableDeclaration
}

StmtPrint: Statement = {
    "echo" <Expr> => Statement::Print {value: <>}
}

StmtVariableDeclaration : Statement = {
    "sit" <varname:"id"> ":" <vartype:"id"> <varvalue:Expr> => Statement::VariableDeclaration {
        value: varvalue,
        variable_type: Some(Symbol::Name(vartype)),
        identifier: Symbol::Name(varname)
    }
}

Expr: Expression = {
    #[precedence(level="1")]
    ExprValue
}

ExprValue: Expression = {
    "catena" => Expression::StringValue {value: <>},
    "id" => Expression::Variable {identifier: Symbol::Name(<>)}
}


